# Generated by Django 5.2.2 on 2025-09-21 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_device_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.FloatField()),
                ('potassium', models.FloatField()),
                ('phosphorus', models.FloatField()),
                ('Temperature', models.FloatField()),
                ('Humidity', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='core.device')),
            ],
        ),
    ]
